# Generated by Django 5.2.8 on 2025-11-19 18:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudesPermiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_permiso', models.CharField(max_length=50)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('dias_solicitados', models.IntegerField(default=0)),
                ('fecha_solicitud', models.DateTimeField(default=django.utils.timezone.now)),
                ('estado', models.CharField(default='Pendiente', max_length=50)),
                ('id_funcionario_solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_enviadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Solicitudes de Permiso',
            },
        ),
    ]
