# Generated by Django 5.2.8 on 2025-11-19 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0002_solicitudespermiso'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudespermiso',
            name='justificativo_archivo',
            field=models.FileField(blank=True, null=True, upload_to='solicitudes/'),
        ),
    ]
