# Generated by Django 5.2.8 on 2025-11-19 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0003_solicitudespermiso_justificativo_archivo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventos_calendario',
            options={'verbose_name_plural': 'Eventos del Calendario'},
        ),
        migrations.AlterField(
            model_name='eventos_calendario',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eventos_calendario',
            name='fecha_inicio',
            field=models.DateField(),
        ),
        migrations.AlterModelTable(
            name='eventos_calendario',
            table='intranet_eventos_calendario',
        ),
    ]
