# Generated by Django 5.2.8 on 2025-11-20 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0005_funcionarios_foto_perfil_mensajes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mensajes',
        ),
    ]
