# Generated by Django 5.2.8 on 2025-11-20 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0006_delete_mensajes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionarios',
            name='foto_perfil',
        ),
    ]
