# Generated by Django 5.2.8 on 2025-11-20 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0007_remove_funcionarios_foto_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentos',
            name='publico',
            field=models.BooleanField(default=False, verbose_name='Es Público'),
        ),
    ]
