# Generated by Django 5.2.8 on 2025-11-20 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0008_documentos_publico'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentos',
            name='roles_permitidos',
            field=models.ManyToManyField(blank=True, related_name='documentos_visibles', to='intranet.roles'),
        ),
    ]
