# Generated by Django 5.2.8 on 2025-12-14 03:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0009_documentos_roles_permitidos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_unidad', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Unidades',
            },
        ),
        migrations.AlterModelOptions(
            name='roles',
            options={'verbose_name_plural': 'Roles'},
        ),
        migrations.AddField(
            model_name='funcionarios',
            name='es_jefe_unidad',
            field=models.BooleanField(default=False, verbose_name='Es Jefe de Unidad'),
        ),
        migrations.AddField(
            model_name='roles',
            name='nivel_jerarquico',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='solicitudespermiso',
            name='aprobado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_aprobadas_final', to=settings.AUTH_USER_MODEL, verbose_name='Aprobado por (Subdirección)'),
        ),
        migrations.AddField(
            model_name='solicitudespermiso',
            name='comentario_rechazo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitudespermiso',
            name='fecha_aprobacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitudespermiso',
            name='fecha_pre_aprobacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitudespermiso',
            name='pre_aprobado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_pre_aprobadas', to=settings.AUTH_USER_MODEL, verbose_name='Pre-aprobado por (Jefe Unidad)'),
        ),
        migrations.AlterField(
            model_name='solicitudespermiso',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Pre-Aprobado', 'Pre-Aprobado'), ('Aprobado', 'Aprobado'), ('Rechazado', 'Rechazado')], default='Pendiente', max_length=50),
        ),
        migrations.AddField(
            model_name='funcionarios',
            name='id_unidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='intranet.unidades'),
        ),
    ]
