# Generated by Django 5.2.8 on 2025-12-14 03:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0010_unidades_alter_roles_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comunicados',
            name='unidad_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comunicados_unidad', to='intranet.unidades', verbose_name='Unidad destino (vacío = todos)'),
        ),
    ]
