# Generated by Django 5.2.8 on 2025-12-14 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0011_comunicados_unidad_destino'),
    ]

    operations = [
        migrations.AddField(
            model_name='dias_administrativos',
            name='anio_saldo',
            field=models.IntegerField(default=2025, verbose_name='Año del saldo'),
        ),
        migrations.AddField(
            model_name='dias_administrativos',
            name='horas_compensacion',
            field=models.IntegerField(default=0, verbose_name='Horas compensación'),
        ),
        migrations.AddField(
            model_name='solicitudespermiso',
            name='horas_solicitadas',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='solicitudespermiso',
            name='observaciones',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='dias_administrativos',
            name='admin_restantes',
            field=models.IntegerField(default=6, verbose_name='Días administrativos'),
        ),
        migrations.AlterField(
            model_name='dias_administrativos',
            name='vacaciones_restantes',
            field=models.IntegerField(default=15, verbose_name='Vacaciones restantes'),
        ),
        migrations.AlterField(
            model_name='solicitudespermiso',
            name='tipo_permiso',
            field=models.CharField(choices=[('administrativo', 'Día Administrativo'), ('vacaciones', 'Feriado Legal (Vacaciones)'), ('sin_goce', 'Permiso sin Goce de Sueldo'), ('hora_medica', 'Hora Médica'), ('licencia', 'Licencia Médica'), ('duelo', 'Permiso por Duelo Familiar'), ('compensacion', 'Compensación de Horas')], max_length=50),
        ),
    ]
