# Generated by Django 5.2.8 on 2025-12-14 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0012_tipos_permiso_y_saldos'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentos',
            name='compartir_jefes',
            field=models.BooleanField(default=False, verbose_name='Compartir con otros Jefes'),
        ),
        migrations.AddField(
            model_name='documentos',
            name='compartir_superiores',
            field=models.BooleanField(default=False, verbose_name='Compartir con superiores'),
        ),
        migrations.AddField(
            model_name='documentos',
            name='compartir_unidad',
            field=models.BooleanField(default=False, verbose_name='Compartir con mi unidad'),
        ),
        migrations.AddField(
            model_name='documentos',
            name='unidad_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='intranet.unidades', verbose_name='Unidad destino específica'),
        ),
        migrations.AlterField(
            model_name='documentos',
            name='publico',
            field=models.BooleanField(default=False, verbose_name='Visible para todos'),
        ),
    ]
